# Generated by Django 2.2.7 on 2019-12-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20191222_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whenemail',
            name='date_reminder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
