# Generated by Django 2.2.7 on 2019-12-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_emaillog_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='is_email_1st',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='is_email_2nd',
            field=models.BooleanField(default=False),
        ),
    ]
