# Generated by Django 2.2.7 on 2019-12-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20191222_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='whenemail',
            name='date_email',
            field=models.IntegerField(default=7),
        ),
    ]
