# Generated by Django 2.2.7 on 2019-12-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20191227_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowingBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('publishing_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name_plural': 'ShowingBooks',
            },
        ),
    ]
